services:
  webhook-server:
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    environment:
      - GITHUB_WEBHOOK_SECRET
    command: uv run uvicorn server:app --host 0.0.0.0 --port 8001
